[config]
startup_project = "F:/Repositories/cpp-evaluation/projects/manuell_spark_norm.toml"
trace_initialdir = "C:/Users/panor/OneDrive/Dokumente/Masterarbeit/Traces"
sensor_initialdir = "C:/Users/panor/AppData/Local/Micro-Epsilon/SensorTool/Protocols"
saveload_initialdir = "./projects"
background_image_initialdir = "C:/Users/panor/Pictures"

