[config]
default_project = "F:/Repositories/cpp-evaluation/projects/manuell_spark_norm.toml"
trace_initialdir = "C:/Users/panor/Downloads"
sensor_initialdir = "C:/Users/panor/AppData/Local/Micro-Epsilon/SensorTool/Protocols"
background_image_initialdir = "C:/Users/panor/Pictures"

